# Generated by Django 5.0.7 on 2024-07-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_delete_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='last_login',
            new_name='data_cadastro',
        ),
    ]
