# Generated by Django 5.0.7 on 2024-07-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_rename_last_login_cliente_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=100)),
                ('column2', models.IntegerField()),
                ('column3', models.DateField()),
            ],
        ),
    ]
