# Generated by Django 5.0.7 on 2024-07-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='choice',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não se aplica', 'Não se aplica')], max_length=20),
        ),
    ]
