# Generated by Django 5.0.7 on 2024-08-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_mymodel_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='choice',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='action',
            field=models.CharField(default='Não se aplica', max_length=20),
        ),
    ]
