# Generated by Django 5.0.7 on 2024-08-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_remove_mymodel_choice_mymodel_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='column4',
            field=models.CharField(default='Valor padrão', max_length=200),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column3',
            field=models.CharField(max_length=200),
        ),
    ]
