# Generated by Django 5.0.7 on 2024-08-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_alter_mymodel_column1_alter_mymodel_column2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column4',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='action',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não se aplica', 'Não se aplica')], default='Não se aplica', max_length=20),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column3',
            field=models.CharField(max_length=255),
        ),
    ]
