# Generated by Django 5.0.7 on 2024-08-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_uploadedfile_remove_mymodel_column4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='column4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
