# Generated by Django 5.0.7 on 2024-08-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_delete_uploadedfile_alter_mymodel_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='column1',
            field=models.TextField(default='default_value', max_length=255),
        ),
    ]
