# Generated by Django 5.0.7 on 2024-08-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_alter_mymodel_column1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='polls.mymodel')),
            ],
        ),
    ]
