# Generated by Django 5.0.7 on 2024-08-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_columndata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='column1',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column2',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column3',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column4',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='ColumnData',
        ),
    ]
