# Generated by Django 5.0.7 on 2024-08-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_remove_mymodel_column1_remove_mymodel_column2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='data',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='column1',
            field=models.TextField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='column2',
            field=models.TextField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='column3',
            field=models.TextField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='column4',
            field=models.TextField(default='Valor padrão'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='action',
            field=models.CharField(default='Não se aplica', max_length=20),
        ),
    ]
