# Generated by Django 5.0.7 on 2024-08-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_remove_mymodel_data_mymodel_column1_mymodel_column2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='action',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column1',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column2',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column3',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column4',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='cis_control',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='cis_sub_control',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='descricao',
            field=models.TextField(default='FDS'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='funcao_de_seguranca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='nist_csf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='nome_da_subcategoria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='tipo_de_ativo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='titulo',
            field=models.CharField(default='FDS', max_length=255),
        ),
    ]
