# Generated by Django 5.0.7 on 2024-08-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_remove_mymodel_action_remove_mymodel_column1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='cis_control',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='cis_sub_control',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='funcao_de_seguranca',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='nist_csf',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='nome_da_subcategoria',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='tipo_de_ativo',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='titulo',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='action',
            field=models.CharField(default='Não se aplica', max_length=20),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='column1',
            field=models.TextField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='column2',
            field=models.TextField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='column3',
            field=models.TextField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='column4',
            field=models.TextField(default='Valor padrão'),
        ),
    ]
