# Generated by Django 5.0.7 on 2024-08-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_mymodel_column5_mymodel_column6_mymodel_column7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column6',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column7',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column8',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
