# Generated by Django 5.0.7 on 2024-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_alter_mymodel_action_alter_mymodel_column1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='column1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column5',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column6',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column7',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='column8',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
