# Generated by Django 5.0.7 on 2024-08-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_alter_mymodel_action_alter_mymodel_column1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='action',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column1',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column2',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column3',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column4',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column5',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column6',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column7',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='column8',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='cis_control',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='cis_sub_control',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='funcao_de_seguranca',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='nist_csf',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='nome_da_subcategoria',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='tipo_de_ativo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
