# Generated by Django 5.0.7 on 2024-08-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_mymodel_upload_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanilhaUpload',
        ),
    ]
