# Generated by Django 5.0.7 on 2024-08-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_delete_planilhaupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='acao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
