# Generated by Django 5.0.7 on 2024-08-12 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_mymodel_acao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelasCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cis_control', models.CharField(max_length=100)),
                ('cis_sub_control', models.CharField(max_length=100)),
                ('tipo_de_ativo', models.CharField(max_length=100)),
                ('funcao_de_seguranca', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('nist_csf', models.CharField(max_length=100)),
                ('nome_da_subcategoria', models.CharField(max_length=255)),
                ('acao', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='acao',
        ),
    ]
