# Generated by Django 5.0.7 on 2024-08-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0050_alter_actionmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actionmodel',
            unique_together={('upload_date', 'acao')},
        ),
    ]
