# Generated by Django 5.0.7 on 2024-08-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0052_alter_actionmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionmodel',
            name='nome',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
