# Generated by Django 5.0.7 on 2024-08-12 20:35

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0053_actionmodel_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionmodel',
            name='upload_date',
            field=models.DateField(default=polls.models.get_current_date),
        ),
    ]
