# Generated by Django 5.0.7 on 2024-08-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0054_alter_actionmodel_upload_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='framework',
        ),
    ]
