# Generated by Django 5.0.7 on 2024-09-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0056_tempactionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempActionModel',
        ),
    ]
