# Generated by Django 5.0.7 on 2024-09-02 12:49

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0059_delete_actiontemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryActionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Default Name', max_length=255)),
                ('cis_control', models.CharField(max_length=100)),
                ('cis_sub_control', models.CharField(max_length=100)),
                ('tipo_de_ativo', models.CharField(max_length=100)),
                ('funcao_de_seguranca', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('nist_csf', models.CharField(max_length=100)),
                ('nome_da_subcategoria', models.CharField(max_length=255)),
                ('acao', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_date', models.DateField(default=polls.models.get_current_date)),
            ],
        ),
    ]
