# Generated by Django 5.1.2 on 2024-10-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0060_temporaryactionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionmodel',
            old_name='cis_control',
            new_name='cis_control5',
        ),
    ]
