# Generated by Django 5.1.2 on 2024-10-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0061_rename_cis_control_actionmodel_cis_control5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionmodel',
            old_name='cis_control5',
            new_name='cis_control',
        ),
    ]
