# Generated by Django 5.1.2 on 2024-11-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0062_rename_cis_control5_actionmodel_cis_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionmodel',
            name='ig',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='framework',
            name='ig',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temporaryactionmodel',
            name='ig',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
