# Generated by Django 5.1.2 on 2024-11-23 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0064_remove_cliente_data_cadastro_remove_cliente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='polls.cliente')),
            ],
            options={
                'db_table': 'polls_log',
            },
        ),
    ]
