# Generated by Django 5.1.2 on 2024-11-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0065_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
