# Generated by Django 5.1.2 on 2024-12-05 17:48

import django.db.models.deletion
import django.utils.timezone
import polls.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Default Name', max_length=255)),
                ('cis_control', models.CharField(max_length=100)),
                ('cis_sub_control', models.CharField(max_length=100)),
                ('tipo_de_ativo', models.CharField(max_length=100)),
                ('funcao_de_seguranca', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('nist_csf', models.CharField(max_length=100)),
                ('ig', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_da_subcategoria', models.CharField(max_length=255)),
                ('acao', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_date', models.DateField(default=polls.models.get_current_date)),
            ],
        ),
        migrations.CreateModel(
            name='framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cis_control', models.CharField(max_length=100)),
                ('cis_sub_control', models.CharField(max_length=100)),
                ('tipo_de_ativo', models.CharField(max_length=100)),
                ('funcao_de_seguranca', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('nist_csf', models.CharField(max_length=100)),
                ('ig', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_da_subcategoria', models.CharField(max_length=255)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryActionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Default Name', max_length=255)),
                ('cis_control', models.CharField(max_length=100)),
                ('cis_sub_control', models.CharField(max_length=100)),
                ('tipo_de_ativo', models.CharField(max_length=100)),
                ('funcao_de_seguranca', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('nist_csf', models.CharField(max_length=100)),
                ('ig', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_da_subcategoria', models.CharField(max_length=255)),
                ('acao', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_date', models.DateField(default=polls.models.get_current_date)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'polls_log',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
